version: '3.7'

volumes:
  postgres_data:

networks:
  travel_agency:
    driver: bridge
  
services:

  web:
    build: ./
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - travel_agency_db
    links:
      - travel_agency_db
    networks:
      - travel_agency

  travel_agency_db:
    image: postgres:13.0-alpine
    restart: 'always'
    container_name: travel_agency_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "${SQL_DATABASE}"
      POSTGRES_USER: "${SQL_USER}"
      POSTGRES_PASSWORD: "${SQL_PASSWORD}"
    ports:
      - "5434:${SQL_PORT}"
    networks:
      - travel_agency