# Generated by Django 3.2.9 on 2021-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drivers'),
    ]

    operations = [
    ]
