# Generated by Django 3.2.9 on 2021-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('document', models.CharField(max_length=15, unique=True)),
                ('names', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('is_whitelist', models.BooleanField(default=True)),

                (
                    'bus',
                    models.ForeignKey(
                        on_delete=models.deletion.DO_NOTHING,
                        to='api.Bus',
                    ),
                ),

                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]