# Generated by Django 3.2.9 on 2021-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('states', models.PositiveSmallIntegerField()),

                (
                    'passenger_id',
                    models.ForeignKey(
                        on_delete=models.deletion.DO_NOTHING,
                        to='api.Passenger',
                    ),
                ),
                (
                    'journey_driver_id',
                    models.ForeignKey(
                        on_delete=models.deletion.DO_NOTHING,
                        to='api.JourneyDriver',
                    ),
                ),
                (
                    'seat_id',
                    models.ForeignKey(
                        on_delete=models.deletion.DO_NOTHING,
                        to='api.Seat',
                    ),
                ),
                
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]